[build]
  base = "backend"
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose", "express", "cors", "helmet", "dotenv"]

[dev]
  command = "cd backend && npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = false
