name: API Testing

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  api-test:
    name: Run API Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          npm ci || npm install
      
      - name: Install e2e-tests dependencies
        working-directory: ./e2e-tests
        run: |
          npm ci || npm install
      
      - name: Build backend
        working-directory: ./backend
        run: |
          npm run build --if-present
      
      - name: Start backend
        working-directory: ./backend
        run: |
          npm start &
        env:
          PORT: 3001
          MONGODB_URI: mongodb://localhost:27017/prompt_hub_test
          NODE_ENV: test
      
      - name: Wait for backend
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: http://localhost:3001
          timeout: 120
      
      - name: Run API tests
        working-directory: ./e2e-tests
        run: |
          npx playwright test
        env:
          API_BASE_URL: http://localhost:3001
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: e2e-tests/test-results
