name: API Testing

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  api-test:
    name: Run API Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          npm install
      
      - name: Install api-tests dependencies
        working-directory: ./api-tests
        run: |
          npm install
      
      - name: Build backend
        working-directory: ./backend
        run: |
          npm run build --if-present
      
      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          sleep 20
          echo "MongoDB should be ready now!"
      
      - name: Start backend
        working-directory: ./backend
        run: |
          npm start &
        env:
          PORT: 3001
          MONGODB_URI: mongodb://localhost:27017/prompt_hub_test
          NODE_ENV: test
      
      - name: Wait for backend
        run: |
          echo "Waiting for backend to be ready..."
          for i in {1..60}; do
            if curl -s http://localhost:3001 > /dev/null; then
              echo "Backend is ready!"
              exit 0
            fi
            echo "Attempt $i: Backend not ready yet, waiting..."
            sleep 2
          done
          echo "Backend failed to start within timeout"
          exit 1
      
      - name: Run API tests
        working-directory: ./api-tests
        run: |
          npx playwright test
        env:
          API_BASE_URL: http://localhost:3001
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: api-tests/test-results
