name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: prompt_hub_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    env:
      NODE_ENV: test
      BASE_URL: http://localhost:3000
      PLAYWRIGHT_BASE_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/prompt_hub_test
      E2E_EMAIL: ${{ secrets.E2E_EMAIL }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Build app
        run: |
          npm run build --if-present

      - name: Start app
        run: |
          npm run start:test --if-present &
          npm run start &
        env:
          PORT: 3000
        shell: bash

      - name: Wait for app to be ready
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: http://localhost:3000
          timeout: 120

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npx playwright test

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report
            test-results
