name: Frontend CI/CD
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  workflow_dispatch:
env:
  NODE_VERSION: '18'
  WORKING_DIR: './frontend'
jobs:
  lint:
    name: Lint Frontend Code
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}
      
      - name: Run ESLint
        run: npm run lint
        working-directory: ${{ env.WORKING_DIR }}
        timeout-minutes: 60
  test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}
      
      - name: Run tests
        run: npm test
        working-directory: ${{ env.WORKING_DIR }}
        timeout-minutes: 60
        env:
          CI: true
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ${{ env.WORKING_DIR }}/test-results/
            ${{ env.WORKING_DIR }}/coverage/
          retention-days: 30
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [lint, test]
    timeout-minutes: 90
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}
      
      - name: Build project
        run: npm run build
        working-directory: ${{ env.WORKING_DIR }}
        timeout-minutes: 60
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ${{ env.WORKING_DIR }}/dist/
          retention-days: 7
